name: FilamentInventory
options:
  bundleIdPrefix: com.sjames
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  FilamentInventory:
    type: application
    platform: iOS
    sources:
      - FilamentInventory
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: com.sjames.filamentinventory
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"

  FilamentInventoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - FilamentInventoryTests
    dependencies:
      - target: FilamentInventory
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FilamentInventory.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FilamentInventory"

schemes:
  FilamentInventory:
    build:
      targets:
        FilamentInventory: all
        FilamentInventoryTests: [test]
    test:
      targets:
        - FilamentInventoryTests
